# Generated by Django 3.2.25 on 2024-05-05 09:48

from django.db import migrations, models
import django.db.models.deletion
import django_resized.forms


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0004_alter_profile_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, unique=True)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('content', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Manufacturer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, unique=True)),
                ('slug', models.SlugField(max_length=200, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pedal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, unique=True)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('description', models.TextField()),
                ('catergory_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='listings.category')),
                ('manufacturer_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='listings.manufacturer')),
            ],
        ),
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, unique=True)),
                ('listing_date', models.DateTimeField(auto_now_add=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.TextField()),
                ('condition', models.CharField(choices=[('As_New', 'As New'), ('Good', 'Good'), ('Well_Used', 'Well Used'), ('Broken', 'Broken')], default='Good', max_length=20)),
                ('image1', django_resized.forms.ResizedImageField(blank=True, crop=None, default='static/images/image_coming_soon.png', force_format='WEBP', keep_meta=True, quality=75, scale=None, size=[1920, 1080], upload_to='static/images')),
                ('image2', django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='WEBP', keep_meta=True, quality=75, scale=None, size=[1920, 1080], upload_to='static/images')),
                ('category_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='listings.category')),
                ('manufacturer_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='listings.manufacturer')),
                ('pedal_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='listings.pedal')),
                ('profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.profile')),
            ],
            options={
                'ordering': ['-listing_date'],
            },
        ),
    ]
