# Generated by Django 3.2.25 on 2024-04-06 15:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Manufacturer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, unique=True)),
                ('slug', models.SlugField(max_length=200, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pedal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, unique=True)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('description', models.TextField()),
                ('catergory_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='listings.category')),
                ('manufacturer_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='listings.manufacturer')),
            ],
        ),
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('listing_date', models.DateTimeField(auto_now_add=True)),
                ('price', models.IntegerField()),
                ('description', models.TextField()),
                ('condition', models.CharField(max_length=200, unique=True)),
                ('catergory_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='listings.category')),
                ('manufacturer_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='listings.manufacturer')),
                ('pedal_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='listings.pedal')),
            ],
        ),
    ]
