# Generated by Django 3.2.25 on 2024-04-20 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0003_auto_20240420_1616'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='condition',
        ),
    ]
