# Generated by Django 3.2.25 on 2024-04-21 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0004_remove_listing_condition'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='catergory_name',
            new_name='category_name',
        ),
        migrations.AddField(
            model_name='listing',
            name='condition',
            field=models.CharField(choices=[('As_New', 'As New'), ('Good', 'Good'), ('Well_Used', 'Well Used'), ('Broken', 'Broken')], default='Good', max_length=20),
        ),
    ]
