# Generated by Django 3.2.25 on 2024-04-27 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0006_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
