# Generated by Django 3.2.25 on 2024-05-04 15:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('listings', '0007_delete_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='image1',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, default='static/images/image_coming_soon.png', force_format='WEBP', keep_meta=True, quality=75, scale=None, size=[1920, 1080], upload_to='static/images'),
        ),
        migrations.AddField(
            model_name='listing',
            name='image2',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, default='static/images/image_coming_soon.png', force_format='WEBP', keep_meta=True, quality=75, scale=None, size=[1920, 1080], upload_to='static/images'),
        ),
        migrations.AddField(
            model_name='listing',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='listing',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
