# Generated by Django 3.2.25 on 2024-05-04 19:19

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0011_alter_listing_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='image2',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='WEBP', keep_meta=True, quality=75, scale=None, size=[1920, 1080], upload_to='static/images'),
        ),
    ]
