# Generated by Django 3.2.25 on 2024-05-04 20:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0014_alter_listing_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='user',
            new_name='profile',
        ),
    ]
